### ISSUE TITLE
MeshToVox: Support of SkinnedMeshRenderer

### ISSUE THREAD

**Issue by X-DE1** [Zarbuz/FileToVox#68]
When I load the .fbx model and start the voxelization, this happens.
![SharedScreenshot](https://user-images.githubusercontent.com/101435795/181153586-27513495-9504-438a-9606-63a58b42502a.jpg)
And when I load the .obj, it doesn't load the textures.
here is the model https://www.models-resource.com/gamecube/spongebobsquarepantsbattleforbikinibottom/model/51644/
I found this tool, poly2vox that transforms 3D models with multiple textures, I think it will be very useful to improve your tool.
http://advsys.net/ken/download.htm#slab6
In this model when i Start Voxeliztion says No Meshes to Combine
![SharedScreenshot2](https://user-images.githubusercontent.com/101435795/181154877-3e23e0fb-57a7-4b32-b317-38eac83b2829.jpg)
here is the model https://www.models-resource.com/custom_edited/mariocustoms/model/43572/

**Comment by Zarbuz** [comment]
Hello,

I was able to succesfully voxelize your first model without any error. You need to active the toggle "Consider Mesh UVs" (with the fbx model) 

I also get the same error with the second model. It's because the model isn't a "classic" mesh but a SkinnedMeshRenderer, I don't support that type of renderer right now. I will try to implement this

**Comment by Zarbuz** [comment]
Version 2.8 will support SkinnedMeshRenderer

**Comment by Zarbuz** [comment]
MeshToVox v2.8 is now available
